// Package main — утилита генерации методов Reset() для структур с комментарием // generate:reset.
//
// Запуск из корня модуля:
//
//	go run ./cmd/reset/
//	go build -o reset ./cmd/reset && ./reset
//
// Сканирует все пакеты от корня проекта, находит структуры с комментарием // generate:reset
// и генерирует для них метод Reset() в файле reset.gen.go в том же пакете.
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

func main() {
	root, err := findModuleRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "find module root: %v\n", err)
		os.Exit(1)
	}

	cfg := &packages.Config{
		Dir:  root,
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
	}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		fmt.Fprintf(os.Stderr, "load packages: %v\n", err)
		os.Exit(1)
	}

	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	for _, pkg := range pkgs {
		if len(pkg.GoFiles) == 0 {
			continue
		}
		// только пакеты внутри модуля (исключаем зависимости)
		pkgDir := filepath.Dir(pkg.GoFiles[0])
		if rel, err := filepath.Rel(root, pkgDir); err != nil || strings.HasPrefix(rel, "..") {
			continue
		}
		structs := findResetStructs(pkg)
		if len(structs) == 0 {
			continue
		}
		outPath := filepath.Join(pkgDir, "reset.gen.go")
		if err := generateResetFile(pkg, structs, outPath); err != nil {
			fmt.Fprintf(os.Stderr, "generate %s: %v\n", outPath, err)
			os.Exit(1)
		}
		fmt.Printf("generated %s (%d structs)\n", outPath, len(structs))
	}
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func findResetStructs(pkg *packages.Package) []*types.Named {
	var out []*types.Named
	for _, f := range pkg.Syntax {
		ast.Inspect(f, func(n ast.Node) bool {
			genDecl, ok := n.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				return true
			}
			if genDecl.Doc == nil {
				return true
			}
			hasMarker := false
			for _, c := range genDecl.Doc.List {
				if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == "generate:reset" {
					hasMarker = true
					break
				}
			}
			if !hasMarker {
				return true
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				_, isStruct := typeSpec.Type.(*ast.StructType)
				if !isStruct {
					continue
				}
				obj := pkg.TypesInfo.Defs[typeSpec.Name]
				if obj == nil {
					continue
				}
				named, ok := obj.Type().(*types.Named)
				if !ok {
					continue
				}
				if _, ok := named.Underlying().(*types.Struct); ok {
					out = append(out, named)
				}
			}
			return true
		})
	}
	return out
}

// resetIface — интерфейс с методом Reset() для проверки вложенных структур.
var resetIface *types.Interface

func init() {
	sig := types.NewSignatureType(nil, nil, nil, nil, nil, false)
	resetIface = types.NewInterfaceType([]*types.Func{types.NewFunc(0, nil, "Reset", sig)}, nil).Complete()
}

func generateResetFile(pkg *packages.Package, structs []*types.Named, outPath string) error {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg.Name + "\n\n")
	for _, named := range structs {
		b.WriteString(generateResetMethod(named))
		b.WriteString("\n")
	}
	src := []byte(b.String())
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile(outPath, formatted, 0644)
}

func generateResetMethod(named *types.Named) string {
	st, _ := named.Underlying().(*types.Struct)
	if st == nil {
		return ""
	}
	typeName := named.Obj().Name()
	recv := receiverName(typeName)
	var b strings.Builder
	b.WriteString("// Reset сбрасывает состояние " + typeName + " к начальным значениям.\n")
	b.WriteString("func (" + recv + " *" + typeName + ") Reset() {\n")
	b.WriteString("\tif " + recv + " == nil {\n\t\treturn\n\t}\n\n")
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		if !f.Exported() && f.Pkg() != nil && f.Pkg().Path() != named.Obj().Pkg().Path() {
			continue
		}
		fieldName := f.Name()
		fieldSel := recv + "." + fieldName
		b.WriteString(emitResetForType(f.Type(), fieldSel, 1))
	}
	b.WriteString("}\n")
	return b.String()
}

func receiverName(typeName string) string {
	for _, r := range typeName {
		return string(unicode.ToLower(r))
	}
	return "r"
}

func emitResetForType(t types.Type, fieldSel string, depth int) string {
	const tab = "\t"
	indent := strings.Repeat(tab, depth)
	indent1 := indent + tab
	indent2 := indent + tab + tab
	switch u := t.Underlying().(type) {
	case *types.Basic:
		zero := zeroValueForBasic(u)
		return indent + fieldSel + " = " + zero + "\n"
	case *types.Slice:
		return indent + fieldSel + " = " + fieldSel + "[:0]\n"
	case *types.Map:
		return indent + "clear(" + fieldSel + ")\n"
	case *types.Pointer:
		elem := u.Elem()
		if named, ok := elem.(*types.Named); ok {
			ptrType := types.NewPointer(named)
			if types.Implements(ptrType, resetIface) {
				var b strings.Builder
				b.WriteString(indent + "if " + fieldSel + " != nil {\n")
				b.WriteString(indent1 + "if resetter, ok := " + fieldSel + ".(interface{ Reset() }); ok {\n")
				b.WriteString(indent2 + "resetter.Reset()\n")
				b.WriteString(indent1 + "}\n")
				b.WriteString(indent + "}\n")
				return b.String()
			}
		}
		elemSel := "*" + fieldSel
		inner := emitResetForType(elem, elemSel, depth+1)
		var b strings.Builder
		b.WriteString(indent + "if " + fieldSel + " != nil {\n")
		b.WriteString(inner)
		b.WriteString(indent + "}\n")
		return b.String()
	case *types.Struct:
		// анонимная структура — только обнуление
		return indent + fieldSel + " = " + typeZeroLiteral(t) + "\n"
	case *types.Named:
		if _, ok := u.Underlying().(*types.Struct); ok {
			return emitResetForStruct(t, fieldSel, depth)
		}
		return emitResetForType(u.Underlying(), fieldSel, depth)
	case *types.Array, *types.Chan, *types.Signature, *types.Interface:
		return indent + fieldSel + " = " + typeZeroLiteral(t) + "\n"
	default:
		return indent + fieldSel + " = " + typeZeroLiteral(t) + "\n"
	}
}

func emitResetForStruct(t types.Type, fieldSel string, depth int) string {
	const tab = "\t"
	indent := strings.Repeat(tab, depth)
	named, _ := t.(*types.Named)
	if named == nil {
		return indent + fieldSel + " = " + typeZeroLiteral(t) + "\n"
	}
	ptrType := types.NewPointer(t)
	if types.Implements(ptrType, resetIface) {
		// поле — структура по значению; для вызова Reset() берём адрес
		return indent + "if resetter, ok := interface{}(&" + fieldSel + ").(interface{ Reset() }); ok {\n" +
			indent + tab + "resetter.Reset()\n" +
			indent + "} else {\n" +
			indent + tab + fieldSel + " = " + typeZeroLiteral(t) + "\n" +
			indent + "}\n"
	}
	return indent + fieldSel + " = " + typeZeroLiteral(t) + "\n"
}

func zeroValueForBasic(b *types.Basic) string {
	switch b.Kind() {
	case types.Bool:
		return "false"
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr:
		return "0"
	case types.Float32, types.Float64:
		return "0"
	case types.Complex64, types.Complex128:
		return "0i"
	case types.String:
		return `""`
	default:
		return "nil"
	}
}

func typeZeroLiteral(t types.Type) string {
	switch u := t.Underlying().(type) {
	case *types.Basic:
		return zeroValueForBasic(u)
	case *types.Slice, *types.Map, *types.Chan, *types.Signature, *types.Interface:
		return "nil"
	case *types.Pointer:
		return "nil"
	case *types.Struct, *types.Array:
		return types.TypeString(t, nil) + "{}"
	case *types.Named:
		// для именованного типа выводим имя (например ResetableStruct{}), а не underlying
		return types.TypeString(t, nil) + "{}"
	default:
		return "nil"
	}
}
